
2020-09-04 17:49:36.893 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-04 17:51:02.866 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-04 18:45:57.852 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-04 18:59:38.194 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-04 21:56:56.107 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-04 21:59:35.286 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-05 09:16:13.343 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 09:44:08.897 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-05 09:47:54.457 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-05 09:49:55.703 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-05 09:51:10.886 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-05 09:52:01.118 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-05 10:02:41.062 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-05 10:07:38.206 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-05 13:15:20.563 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 13:18:08.457 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 13:20:43.971 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 13:21:56.961 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 13:57:48.728 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 13:58:48.012 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 14:02:31.277 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 14:08:27.367 [main] ERROR org.springframework.test.context.TestContextManager              - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@63b1d4fa] to prepare test instance [application.controller.ApiAuthControllerTest@5acc9fdf]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application.controller.ApiAuthControllerTest': Unsatisfied dependency expressed through field 'ctx'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.web.context.WebApplicationContext' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireBeanProperties(AbstractAutowireCapableBeanFactory.java:393) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:119) ~[spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83) ~[spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53) [junit-rt.jar:?]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.web.context.WebApplicationContext' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1700) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1256) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 27 more
2020-09-05 14:11:17.883 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter              - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in application.controller.ApiAuthController required a bean of type 'application.service.UserServiceImpl' that could not be found.


Action:

Consider defining a bean of type 'application.service.UserServiceImpl' in your configuration.

2020-09-05 14:11:17.884 [main] ERROR org.springframework.test.context.TestContextManager              - Caught exception while allowing TestExecutionListener [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@3c9168dc] to prepare test instance [application.controller.ApiAuthControllerTest@553d2579]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132) ~[spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123) ~[spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.postProcessFields(MockitoTestExecutionListener.java:95) ~[spring-boot-test-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.injectFields(MockitoTestExecutionListener.java:79) ~[spring-boot-test-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener.prepareTestInstance(MockitoTestExecutionListener.java:54) ~[spring-boot-test-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:244) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190) [spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53) [junit-rt.jar:?]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'apiAuthController' defined in file [/Users/alex/the_thesis/target/classes/application/controller/ApiAuthController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'application.service.UserServiceImpl' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:798) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:126) ~[spring-boot-test-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) ~[spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 25 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'application.service.UserServiceImpl' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1700) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1256) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1210) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:885) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:789) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:228) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:126) ~[spring-boot-test-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99) ~[spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124) ~[spring-test-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 25 more
2020-09-05 14:12:13.728 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 15:10:30.879 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 15:14:26.797 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 15:15:16.459 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 15:18:08.351 [main] ERROR application.exception.GlobalExceptionHandler              - null
2020-09-05 20:32:36.279 [http-nio-8080-exec-3] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, null
2020-09-05 21:07:50.999 [http-nio-8080-exec-4] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, null
2020-09-05 22:13:02.944 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
2020-09-05 22:13:59.714 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 3; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 3
2020-09-05 22:14:43.611 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 4; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 4
2020-09-05 22:16:22.675 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 5; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 5
2020-09-05 22:17:35.737 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 6; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 6
2020-09-05 22:19:32.778 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 7; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 7
2020-09-05 22:20:12.659 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 8; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 8
2020-09-05 22:20:44.273 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 9; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 9
2020-09-05 22:21:20.678 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 10; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 10
2020-09-05 22:22:18.575 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 11; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 11
2020-09-05 22:23:35.306 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 12; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 12
2020-09-05 22:24:14.011 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 13; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 13
2020-09-05 22:28:16.241 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
2020-09-05 22:31:31.788 [main] ERROR application.exception.GlobalExceptionHandler              - query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
2020-09-08 13:10:02.365 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-08 16:56:19.869 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-10 16:31:16.086 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-10 16:31:53.570 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-10 16:52:54.508 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-10 16:58:20.147 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-10 16:59:10.703 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-10 17:06:52.468 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-10 17:07:40.050 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-10 17:14:13.633 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:13.720 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:13.813 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.082 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.127 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-10 17:14:14.154 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.256 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.370 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.444 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.487 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.652 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.704 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.750 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.875 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:14.921 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:49.710 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:49.927 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:49.968 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.020 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.148 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.200 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.226 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-10 17:14:50.250 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.352 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.491 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.568 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.653 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.703 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.792 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.849 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.902 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:50.958 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:51.028 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:51.123 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:51.175 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:51.215 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:14:51.249 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:27.624 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:27.682 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:27.743 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:27.889 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:27.920 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-10 17:17:27.947 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.031 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.207 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.318 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.364 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.549 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.610 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.672 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.832 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:17:28.931 [main] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper              - ERROR: update or delete on table "posts" violates foreign key constraint "post_comments_post_fk" on table "post_comments"
  Detail: Key (id)=(1) is still referenced from table "post_comments".
2020-09-10 17:21:27.277 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-10 17:23:18.939 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-14 19:36:26.554 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-14 19:39:20.102 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-15 12:42:33.368 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-15 15:56:20.816 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-15 16:03:56.984 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-15 16:49:59.282 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-15 16:51:01.582 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-15 16:51:32.588 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-15 17:38:40.029 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-15 17:39:35.821 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-15 17:41:09.137 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.EntNotFoundException, post id: 10000
2020-09-15 17:42:58.223 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
2020-09-15 17:43:44.995 [main] ERROR application.exception.GlobalExceptionHandler              - application.exception.UserUnauthenticatedException, null
